baseURL = 'https://ai-tankesmedjan.onrender.com/'
languageCode = 'sv-SE'
title = 'Tankesmedjan AI-revolutionen'
theme = "forty"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]

  # Provide your metadata here.
  name = ""
  description = "Tankesmedjan AI-revolutionen"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  # TODO: Remove params
  [params.navigation]
    title = "Tankesmedjan AI-revolutionen"
    subtitle = "- en framtidsvision -"
    menu = "Menu"
    # Optional logo as brand stored in img/
    logo = "logo.jpeg"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Tankesmedjan AI-revolutionen"
    subtitle = "Där tar AI vid"
    buttonText = "Starta"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Blog"
      subtitle = ""
      image = ""
      url = "blogs/"

    [[params.tiles.showcase]]
      subtitle = ""
      title = "Insikter, längre texter och utvik"
      image = "catalog-small.jpg"
      url = "insikt"

    [[params.tiles.showcase]]
      subtitle = ""
      title = "Länkar till andra"
      image = ""
      url = "links"

    [[params.tiles.showcase]]
      subtitle = ""
      title = "Nya arbetssätt"
      image = ""
      url = "arbetssatt"

    [[params.tiles.showcase]]
      subtitle = ""
      title = "AI-Ops och ML-Ops"
      image = ""
      url = "aiops"

    [[params.tiles.showcase]]
      subtitle = ""
      title = "Vilka är vi?"
      image = ""
      url = "about"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.
  
  # Footer section
  [params.footer]
    enable = true
    copyright = "Tankesmedjan AI-revolutionen"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/aitankesmedjan"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/aitankesmedjan"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/company/tankesmedjan-ai-revolutionen/"
      label = "LinkedIn"
